### ISSUE TITLE
should be "output = model(tokens)[-1, 0]"?

### ISSUE THREAD

**Issue by sunrainmao** [maxDeCoder/Mamba-tf#1]
def infer(text: str, model: Model, tokenizer):
    tokens = tokenizer.encode("Hello what is up", max_length=args.seq_length, padding='max_length', return_tensors='np')
    output = model(tokens)[0, 0]
    return output

should be output = model(tokens)[-1, 0]? I guess?

**Comment by vedant-jumle** [comment]
Yup, I will fix this
