### ISSUE TITLE
I think A_log is trainable, right?

### ISSUE THREAD

**Issue by sunrainmao** [maxDeCoder/Mamba-tf#2]
Here is the codes:
self.A_log = tf.Variable(tf.math.log(self.A), trainable=False, dtype=tf.float32)

the below is the pytorch code from the Mamba open source code:
# S4D real initialization
        A = repeat(
            torch.arange(1, self.d_state + 1, dtype=torch.float32, device=device),
            "n -> d n",
            d=self.d_inner,
        ).contiguous()
        A_log = torch.log(A)  # Keep A_log in fp32
        self.A_log = nn.Parameter(A_log)
        self.A_log._no_weight_decay = True

        # D "skip" parameter
        self.D = nn.Parameter(torch.ones(self.d_inner, device=device))  # Keep in fp32
        self.D._no_weight_decay = True

**Comment by vedant-jumle** [comment]
You are right. A_log should be trainable.
